version: '3.4'
services:
  dwhlanding:
      image: kenyahmis/dwhlanding:${TAG}
      container_name: dwhlanding
      restart: always
      environment:
        - REACT_APP_API_URL=${APP_API_URL}
      ports:
        - "${APP_PORT}:${APP_HOST_PORT}"